# Generated by Django 4.2 on 2024-01-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoExteriorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pais', models.IntegerField()),
                ('endereco_completo_exterior', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nfse_endereco_exterior',
            },
        ),
        migrations.CreateModel(
            name='EnderecoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=125)),
                ('numero', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=60, null=True)),
                ('bairro', models.CharField(max_length=60)),
                ('codigo_municipio', models.CharField(max_length=7)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'nfse_endereco',
            },
        ),
        migrations.CreateModel(
            name='InfoNFseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfse_substituida', models.IntegerField(null=True, unique=True)),
                ('outras_informacoes', models.CharField(max_length=510, null=True)),
                ('data_emissao', models.DateTimeField()),
                ('competencia', models.DateField()),
                ('regime_tributacao', models.IntegerField(choices=[(1, 'Microempresa Municipal'), (2, 'Estimativa'), (3, 'Sociedade de Profissionais'), (4, 'Cooperativa'), (5, 'Microempresário Individual (MEI)'), (6, 'Microempresa ou Empresa de Pequeno Porte (ME EPP)')], null=True)),
                ('optante_simples_nacional', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')])),
                ('incentivo_fiscal', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')])),
            ],
            options={
                'db_table': 'nfse_info',
            },
        ),
        migrations.CreateModel(
            name='IntermediarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14, null=True)),
                ('inscricao_muncipal', models.CharField(max_length=15, null=True)),
                ('razao_social', models.CharField(max_length=150, null=True)),
                ('codigo_municipio', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'nfse_intermediario',
            },
        ),
        migrations.CreateModel(
            name='RpsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('serie', models.CharField(default='ÚNICA', max_length=5)),
                ('tipo', models.IntegerField(choices=[(1, 'Recibo Provisório de Serviços'), (2, 'RPS Nota Fiscal Conjugada (Mista)'), (3, 'Cupom')])),
                ('numero_substituido', models.IntegerField(null=True)),
                ('serie_substituido', models.CharField(max_length=5, null=True)),
                ('tipo_substituido', models.IntegerField(choices=[(1, 'Recibo Provisório de Serviços'), (2, 'RPS Nota Fiscal Conjugada (Mista)'), (3, 'Cupom')], null=True)),
                ('data_emissao_rps', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Normal'), (2, 'Cancelado')])),
            ],
            options={
                'db_table': 'nfse_rps',
            },
        ),
        migrations.CreateModel(
            name='ServicoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriminacao', models.CharField(max_length=2000)),
                ('iss_retido', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')])),
                ('responsavel_retencao', models.IntegerField(choices=[(1, 'Tomador'), (2, 'Intermediário')], null=True)),
                ('item_lista_servico', models.CharField(max_length=5)),
                ('codigo_cnae', models.IntegerField(null=True)),
                ('codigo_tributacao_municipio', models.CharField(max_length=20, null=True)),
                ('codigo_nbs', models.CharField(max_length=9, null=True)),
                ('codigo_municipio', models.IntegerField()),
                ('codigo_pais', models.IntegerField(null=True)),
                ('exibilidade_iss', models.IntegerField(choices=[(1, 'Exígivel'), (2, 'Não Incidência'), (3, 'Isenção'), (4, 'Exportação'), (5, 'Imunidade'), (6, 'Exigibilidade Suspensa por Decisão Judicial'), (7, ' Exigibilidade Suspensa por Processo Administrativo')])),
                ('identificacao_nao_exigibilidade', models.CharField(max_length=4, null=True)),
                ('municipio_incidencia', models.IntegerField(null=True)),
                ('numero_processo', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'nfse_servico',
            },
        ),
        migrations.CreateModel(
            name='ValoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('valor_liquido_nfse', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_servicos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_deducoes', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_pis', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_cofins', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_inss', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_ir', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_csll', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('outras_retencoes', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_total_tributos', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valor_iss', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('aliquota_servico', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('desconto_incodicionado', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('desconto_condicionado', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'nfse_model',
            },
        ),
        migrations.CreateModel(
            name='TomadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('inscricao_muncipal', models.CharField(max_length=15, null=True)),
                ('nif_tomador', models.CharField(max_length=40, null=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.enderecomodel')),
                ('endereco_exterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfse.enderecoexteriormodel')),
            ],
            options={
                'db_table': 'nfse_tomador',
            },
        ),
        migrations.CreateModel(
            name='PrestadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(max_length=60, null=True)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('inscricao_muncipal', models.CharField(max_length=15, null=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.enderecomodel')),
            ],
            options={
                'db_table': 'nfse_prestador',
            },
        ),
        migrations.CreateModel(
            name='NfseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('municipio_prefeitura', models.CharField(max_length=50)),
                ('quem_lancou', models.CharField(max_length=30)),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.infonfsemodel')),
            ],
            options={
                'db_table': 'nfse',
            },
        ),
        migrations.AddField(
            model_name='infonfsemodel',
            name='intermediario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfse.intermediariomodel'),
        ),
        migrations.AddField(
            model_name='infonfsemodel',
            name='prestador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.prestadormodel'),
        ),
        migrations.AddField(
            model_name='infonfsemodel',
            name='rps',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.rpsmodel'),
        ),
        migrations.AddField(
            model_name='infonfsemodel',
            name='servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.servicomodel'),
        ),
        migrations.AddField(
            model_name='infonfsemodel',
            name='tomador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.tomadormodel'),
        ),
        migrations.AddField(
            model_name='infonfsemodel',
            name='valores',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfse.valoresmodel'),
        ),
    ]
