# Generated by Django 4.2 on 2024-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonfsemodel',
            name='data_emissao',
            field=models.DateTimeField(null=True),
        ),
    ]
