# Generated by Django 4.2 on 2024-05-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestadormodel',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='nfsemodel',
            name='ambiente',
            field=models.CharField(choices=[('PD', 'Produção'), ('HM', 'Homologação')], max_length=2),
        ),
    ]
